

   <ul>
	<li><a href='sites/bagelmania.com/files/PDF/bagels.pdf' title='Bagel' >Bagels</a></li>	
	<li><a href='sites/bagelmania.com/files/PDF/bagels2.pdf' title='Bagel2'>Bagels Too</a></li>	
	<li><a href='sites/bagelmania.com/files/PDF/coffee.pdf' title='Coffee' >Coffee</a></li>	
	<li><a href='sites/bagelmania.com/files/PDF/mainMenu.pdf' title='Main Menu' >Main Menu</a></li>	
	<li><a href='sites/bagelmania.com/files/PDF/smoothieMenu.pdf' title='Smoothies' >Smoothies</a></li>
  </ul>  
	
     
	 
 
 
 
 
 

